/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <libs/include/log_producer_client.h>
#include <android/looper.h>
#include <unistd.h>

/* Header for class com_aliyun_sls_android_producer_LogProducerClient */

#ifndef _Included_com_aliyun_sls_android_producer_LogProducerClient
#define _Included_com_aliyun_sls_android_producer_LogProducerClient
#ifdef __cplusplus
extern "C" {
#endif

extern JavaVM *g_VM;
extern ALooper *main_thread_looper;
static int message_pipe[2];
static int looper_init_flag = 0;

typedef struct _callback_data {
    const char *config_name;
    log_producer_result result;
    size_t log_bytes;
    size_t compressed_bytes;
    const char *req_id;
    const char *error_message;
    jobject callback;
} callback_data;


static void _call_jni_fun(JNIEnv *env,
                          jobject callback,
                          const char *config_name,
                          log_producer_result result,
                          size_t log_bytes,
                          size_t compressed_bytes,
                          const char * req_id,
                          const char * error_message)
{
    jclass java_class = (*env)->GetObjectClass(env, callback);
    if (java_class == 0) {
        (*g_VM)->DetachCurrentThread(g_VM);
        return;
    }

    jmethodID java_callback_id = (*env)->GetMethodID(env, java_class,
                                                     "onCall",
                                                     "(ILjava/lang/String;Ljava/lang/String;II)V");
    if (java_callback_id == NULL) {
        return;
    }

    jstring req_id_jstr_buf = (*env)->NewStringUTF(env, req_id);
    jstring message_jstr_buf = (*env)->NewStringUTF(env, error_message);
    (*env)->CallVoidMethod(env, callback, java_callback_id, result, req_id_jstr_buf, message_jstr_buf,
                           log_bytes, compressed_bytes);
}

void on_log_send_done(const char *config_name,
                      log_producer_result result,
                      size_t log_bytes,
                      size_t compressed_bytes,
                      const char * req_id,
                      const char * error_message,
                      const unsigned char * raw_buffer,
                      void *params)
{
    if (message_pipe[1])
    {
        callback_data data = {
                config_name, result, log_bytes, compressed_bytes, req_id, error_message, params
        };
        write(message_pipe[1], &data, sizeof(callback_data));
    }
    else
    {
        JNIEnv *env = NULL;
        if ((*g_VM)->AttachCurrentThread(g_VM, &env, NULL) != JNI_OK) {
            return;
        }

        _call_jni_fun(env, (jobject) params, config_name, result, log_bytes, compressed_bytes, req_id, error_message);
        (*g_VM)->DetachCurrentThread(g_VM);
        env = NULL;
    }
}

static int looper_callback(int fd, int events, void* data)
{
    callback_data cbk_data;
    read(fd, &cbk_data, sizeof(callback_data));

    const char *config_name = cbk_data.config_name;
    log_producer_result result = cbk_data.result;
    size_t log_bytes = cbk_data.log_bytes;
    size_t compressed_bytes = cbk_data.compressed_bytes;
    const char * req_id = cbk_data.req_id;
    const char * error_message = cbk_data.error_message;
    jobject callback = cbk_data.callback;

    JNIEnv *env = NULL;
    int status = (*g_VM)->GetEnv(g_VM, (void **)&env, JNI_VERSION_1_6);
    if (JNI_EDETACHED == status || NULL == env) {
        if ((*g_VM)->AttachCurrentThread(g_VM, &env, NULL) != JNI_OK) {
            return 1;
        }
    }

    _call_jni_fun(env, callback, config_name, result, log_bytes, compressed_bytes, req_id, error_message);
    env = NULL;
    return 1;
}

static void _init_main_looper_pipe()
{
    if (!looper_init_flag && main_thread_looper)
    {
        looper_init_flag = 1;

        ALooper_acquire(main_thread_looper);
        pipe(message_pipe);
        ALooper_addFd(main_thread_looper, message_pipe[0], 0, ALOOPER_EVENT_INPUT, looper_callback, NULL);
    }
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerClient
 * Method:    create_log_producer
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jlong JNICALL
Java_com_aliyun_sls_android_producer_LogProducerClient_create_1log_1producer
        (JNIEnv *env, jclass obj, jlong config, jobject callback) {
    if (callback == NULL) {
        return (jlong) create_log_producer((log_producer_config *) config, NULL, NULL);
    }

    jobject c_callback = (*env)->NewGlobalRef(env, callback);
    _init_main_looper_pipe();
    return (jlong) create_log_producer((log_producer_config *) config, on_log_send_done, c_callback);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerClient
 * Method:    get_log_producer_client
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jlong JNICALL
Java_com_aliyun_sls_android_producer_LogProducerClient_get_1log_1producer_1client
        (JNIEnv *env, jclass obj, jlong producer) {
    return (jlong) get_log_producer_client((log_producer *) producer, NULL);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerClient
 * Method:    log_producer_client_add_log_with_len
 * Signature: (Ljava/lang/Object;I[Ljava/lang/String;[I[Ljava/lang/String;[I)V
 */
JNIEXPORT jint JNICALL
Java_com_aliyun_sls_android_producer_LogProducerClient_log_1producer_1client_1add_1log_1with_1len
        (JNIEnv *env, jclass obj, jlong config, jlong log_time, jint pair_count, jobjectArray keys,
         jobjectArray values, jint flush) {
    int i;
    jsize len_keys = (*env)->GetArrayLength(env, keys);
    jstring jstr_keys[len_keys];
    char **c_keys = (char **) malloc(len_keys * sizeof(char *));
    int32_t *c_key_lens = (int32_t *) malloc(len_keys * sizeof(int32_t));
    for (i = 0; i < len_keys; i++) {
        jstr_keys[i] = (*env)->GetObjectArrayElement(env, keys, i);
        c_keys[i] = (char *) (*env)->GetStringUTFChars(env, jstr_keys[i], 0);
        c_key_lens[i] = strlen(c_keys[i]);
    }
    jsize len_values = (*env)->GetArrayLength(env, values);
    jstring jstr_values[len_values];
    char **c_values = (char **) malloc(len_values * sizeof(char *));
    int32_t *c_value_lens = (int32_t *) malloc(len_values * sizeof(int32_t));
    for (i = 0; i < len_values; i++) {
        jstr_values[i] = (*env)->GetObjectArrayElement(env, values, i);
        c_values[i] = (char *) (*env)->GetStringUTFChars(env, jstr_values[i], 0);
        c_value_lens[i] = strlen(c_values[i]);
    }

    int res = log_producer_client_add_log_with_len_time_int32((log_producer_client *) config, log_time, pair_count,
                                                         c_keys, c_key_lens, c_values, c_value_lens,
                                                         flush);

    for (i = 0; i < len_keys; i++) {
        (*env)->ReleaseStringUTFChars(env, jstr_keys[i], c_keys[i]);
    }
    for (i = 0; i < len_values; i++) {
        (*env)->ReleaseStringUTFChars(env, jstr_values[i], c_values[i]);
    }
    free(c_keys);
    free(c_key_lens);
    free(c_values);
    free(c_value_lens);
    return res;
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerClient
 * Method:    destroy_log_producer
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerClient_destroy_1log_1producer
        (JNIEnv *env, jclass obj, jlong producer) {
    destroy_log_producer((log_producer *) producer);
}

/*
 * Class: com_aliyun_sls_android_producer_LogProducerClient
 * Method: log_producer_client_add_log_with_len_time_int32
 */
JNIEXPORT jint JNICALL
Java_com_aliyun_sls_android_producer_LogProducerClient_log_1producer_1client_1add_1log_1with_1len_1time_1int32(
        JNIEnv *env, jclass clazz, jlong config, jlong log_time, jint pair_count, jobjectArray keys,
        jobjectArray values) {
    jsize len_keys = (*env)->GetArrayLength(env, keys);
    jobjectArray key_array[len_keys];
    char **c_keys = (char **) malloc(len_keys * sizeof(char *));
    int32_t *c_key_lens = (int32_t *) malloc(len_keys * sizeof(int32_t));
    int i;
    for (i = 0; i < len_keys; i++) {
        key_array[i] = (*env)->GetObjectArrayElement(env, keys, i);
        jsize cols = (*env)->GetArrayLength(env, key_array[i]);
        c_keys[i] = (char *) (*env)->GetByteArrayElements(env, key_array[i], 0);
        c_key_lens[i] = cols;
    }

    jsize len_values = (*env)->GetArrayLength(env, values);
    jobjectArray value_array[len_values];
    char **c_values = (char **) malloc(len_values * sizeof(char *));
    int32_t *c_value_lens = (int32_t *) malloc(len_values * sizeof(int32_t));
    for (i = 0; i < len_values; i++) {
        value_array[i] = (*env)->GetObjectArrayElement(env, values, i);
        jsize cols = (*env)->GetArrayLength(env, value_array[i]);
        c_values[i] = (char *) (*env)->GetByteArrayElements(env, value_array[i], 0);
        c_value_lens[i] = cols;
    }

    int res = log_producer_client_add_log_with_len_time_int32((log_producer_client *) config, log_time, pair_count,
                                                              c_keys, c_key_lens, c_values, c_value_lens,
                                                              0);

    for (i = 0; i < len_keys; i++) {
        (*env)->ReleaseByteArrayElements(env, key_array[i], (jbyte *)c_keys[i], JNI_COMMIT);
    }
    for (i = 0; i < len_values; i++) {
        (*env)->ReleaseByteArrayElements(env, value_array[i], (jbyte *)c_values[i], JNI_COMMIT);
    }
    free(c_keys);
    free(c_key_lens);
    free(c_values);
    free(c_value_lens);
    return res;
}

#ifdef __cplusplus
}
#endif
#endif
