/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <curl/curl.h>
#include <libs/producer/include/inner_log.h>
#include "libs/producer/include/log_producer_config.h"

/* Header for class com_aliyun_sls_android_producer_LogProducerConfig */

#ifndef _Included_com_aliyun_sls_android_producer_LogProducerConfig
#define _Included_com_aliyun_sls_android_producer_LogProducerConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    create_log_producer_config
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jlong JNICALL Java_com_aliyun_sls_android_producer_LogProducerConfig_create_1log_1producer_1config
  (JNIEnv *env, jclass obj, jboolean is_debug_enabled){
    if (is_debug_enabled) {
        aos_log_set_level(AOS_LOG_DEBUG);
    }
    return create_log_producer_config();
  }

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_endpoint
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1endpoint
  (JNIEnv *env, jclass obj, jlong config, jstring endpoint){
    const char *c_endpoint = (*env)->GetStringUTFChars(env, endpoint, NULL);
    log_producer_config_set_endpoint((log_producer_config *)config, c_endpoint);
  }

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_project
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1project
  (JNIEnv *env, jclass obj, jlong config, jstring project){
    const char *c_project = (*env)->GetStringUTFChars(env, project, NULL);
    log_producer_config_set_project((log_producer_config *)config, c_project);
  }

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_logstore
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1logstore
  (JNIEnv *env, jclass obj, jlong config, jstring logstore){
    const char *c_logstore = (*env)->GetStringUTFChars(env, logstore, NULL);
    log_producer_config_set_logstore((log_producer_config *)config, c_logstore);
  }

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_access_id
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1access_1id
  (JNIEnv *env, jclass obj, jlong config, jstring accessKey_id){
    const char *c_accessKey_id = (*env)->GetStringUTFChars(env, accessKey_id, NULL);
    log_producer_config_set_access_id((log_producer_config *)config, c_accessKey_id);
  }

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_access_key
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1access_1key
  (JNIEnv *env, jclass obj, jlong config, jstring access_key_secret){
    const char *c_access_key_secret = (*env)->GetStringUTFChars(env, access_key_secret, NULL);
    log_producer_config_set_access_key((log_producer_config *)config, c_access_key_secret);
  }

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_reset_security_token
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1reset_1security_1token
        (JNIEnv *env, jclass obj, jlong config, jstring accessKey_id, jstring access_key_secret, jstring security_token){
    const char *c_accessKey_id = (*env)->GetStringUTFChars(env, accessKey_id, NULL);
    const char *c_access_key_secret = (*env)->GetStringUTFChars(env, access_key_secret, NULL);
    const char *c_security_token = (*env)->GetStringUTFChars(env, security_token, NULL);
    log_producer_config_reset_security_token((log_producer_config *)config, c_accessKey_id, c_access_key_secret, c_security_token);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_topic
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1topic
  (JNIEnv *env, jclass obj, jlong config, jstring topic){
    const char *c_topic = (*env)->GetStringUTFChars(env, topic, NULL);
    log_producer_config_set_topic((log_producer_config *)config, c_topic);
  }

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_add_tag
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1add_1tag
  (JNIEnv *env, jclass obj, jlong config, jstring key, jstring value){
    const char *c_key = (*env)->GetStringUTFChars(env, key, NULL);
    const char *c_value = (*env)->GetStringUTFChars(env, value, NULL);
    log_producer_config_add_tag((log_producer_config *)config, c_key, c_value);
  }

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_packet_log_bytes
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1packet_1log_1bytes
  (JNIEnv *env, jclass obj, jlong config, jint num){
    log_producer_config_set_packet_log_bytes((log_producer_config *)config, num);
  }

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_packet_log_count
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1packet_1log_1count
  (JNIEnv *env, jclass obj, jlong config, jint num){
    log_producer_config_set_packet_log_count((log_producer_config *)config, num);
  }

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_packet_timeout
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1packet_1timeout
  (JNIEnv *env, jclass obj, jlong config, jint num){
    log_producer_config_set_packet_timeout((log_producer_config *)config, num);
  }

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_max_buffer_limit
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1max_1buffer_1limit
  (JNIEnv *env, jclass obj, jlong config, jint num){
    log_producer_config_set_max_buffer_limit((log_producer_config *)config, num);
  }

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_send_thread_count
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1send_1thread_1count
  (JNIEnv *env, jclass obj, jlong config, jint num){
    log_producer_config_set_send_thread_count((log_producer_config *)config, num);
  }

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_persistent
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1persistent
        (JNIEnv *env, jclass obj, jlong config, jint num){
    log_producer_config_set_persistent((log_producer_config *)config, num);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_persistent_file_path
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1persistent_1file_1path
        (JNIEnv *env, jclass obj, jlong config, jstring path){
    const char *c_path = (*env)->GetStringUTFChars(env, path, NULL);
    log_producer_config_set_persistent_file_path((log_producer_config *)config, c_path);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_persistent_force_flush
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1persistent_1force_1flush
        (JNIEnv *env, jclass obj, jlong config, jint num){
    log_producer_config_set_persistent_force_flush((log_producer_config *)config, num);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_persistent_max_file_count
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1persistent_1max_1file_1count
        (JNIEnv *env, jclass obj, jlong config, jint num){
    log_producer_config_set_persistent_max_file_count((log_producer_config *)config, num);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_persistent_max_file_size
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1persistent_1max_1file_1size
        (JNIEnv *env, jclass obj, jlong config, jint num){
    log_producer_config_set_persistent_max_file_size((log_producer_config *)config, num);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_persistent_max_log_count
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1persistent_1max_1log_1count
        (JNIEnv *env, jclass obj, jlong config, jint num){
    log_producer_config_set_persistent_max_log_count((log_producer_config *)config, num);
}

void curl_init() {
    curl_easy_init();
}

#ifdef __cplusplus
}
#endif
#endif
