/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <libs/include/inner_log.h>
#include <libs/include/log_producer_config.h>
#include <libs/include/log_http_interface.h>
#include "sls_android_http_inject.h"

/* Header for class com_aliyun_sls_android_producer_LogProducerConfig */

#ifndef _Included_com_aliyun_sls_android_producer_LogProducerConfig
#define _Included_com_aliyun_sls_android_producer_LogProducerConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    create_log_producer_config
 * Signature: ()V
 */
JNIEXPORT jlong JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_create_1log_1producer_1config
        (JNIEnv *env, jclass obj) {
    return (jlong) create_log_producer_config();
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_debug
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1debug
        (JNIEnv *env, jclass obj) {
    aos_log_set_level(AOS_LOG_TRACE);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_endpoint
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1endpoint
        (JNIEnv *env, jclass obj, jlong config, jstring endpoint) {
    if (NULL == endpoint) {
        log_producer_config_set_endpoint((log_producer_config *) config, NULL);
        return;
    }

    const char *c_endpoint = (*env)->GetStringUTFChars(env, endpoint, NULL);
    log_producer_config_set_endpoint((log_producer_config *) config, c_endpoint);
    (*env)->ReleaseStringUTFChars(env, endpoint, c_endpoint);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_project
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1project
        (JNIEnv *env, jclass obj, jlong config, jstring project) {
    if (NULL == project) {
        log_producer_config_set_project((log_producer_config *) config, NULL);
        return;
    }

    const char *c_project = (*env)->GetStringUTFChars(env, project, NULL);
    log_producer_config_set_project((log_producer_config *) config, c_project);
    (*env)->ReleaseStringUTFChars(env, project, c_project);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_logstore
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1logstore
        (JNIEnv *env, jclass obj, jlong config, jstring logstore) {
    if (NULL == logstore) {
        log_producer_config_set_logstore((log_producer_config *) config, NULL);
        return;
    }

    const char *c_logstore = (*env)->GetStringUTFChars(env, logstore, NULL);
    log_producer_config_set_logstore((log_producer_config *) config, c_logstore);
    (*env)->ReleaseStringUTFChars(env, logstore, c_logstore);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_access_id
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1access_1id
        (JNIEnv *env, jclass obj, jlong config, jstring accessKey_id) {
    if (NULL == accessKey_id) {
        log_producer_config_set_access_id((log_producer_config *) config, NULL);
        return;
    }

    const char *c_accessKey_id = (*env)->GetStringUTFChars(env, accessKey_id, NULL);
    log_producer_config_set_access_id((log_producer_config *) config, c_accessKey_id);
    (*env)->ReleaseStringUTFChars(env, accessKey_id, c_accessKey_id);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_access_key
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1access_1key
        (JNIEnv *env, jclass obj, jlong config, jstring access_key_secret) {
    if (NULL == access_key_secret) {
        log_producer_config_set_access_key((log_producer_config *) config, NULL);
        return;
    }

    const char *c_access_key_secret = (*env)->GetStringUTFChars(env, access_key_secret, NULL);
    log_producer_config_set_access_key((log_producer_config *) config, c_access_key_secret);
    (*env)->ReleaseStringUTFChars(env, access_key_secret, c_access_key_secret);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_reset_security_token
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1reset_1security_1token
        (JNIEnv *env, jclass obj, jlong config, jstring accessKey_id, jstring access_key_secret,
         jstring security_token) {
     if (NULL == accessKey_id || NULL == access_key_secret || NULL == security_token) {
         log_producer_config_reset_security_token((log_producer_config *) config, NULL,
                                                  NULL, NULL);
        return;
     }

    const char *c_accessKey_id = (*env)->GetStringUTFChars(env, accessKey_id, NULL);
    const char *c_access_key_secret = (*env)->GetStringUTFChars(env, access_key_secret, NULL);
    const char *c_security_token = (*env)->GetStringUTFChars(env, security_token, NULL);
    log_producer_config_reset_security_token((log_producer_config *) config, c_accessKey_id,
                                             c_access_key_secret, c_security_token);
    (*env)->ReleaseStringUTFChars(env, accessKey_id, c_accessKey_id);
    (*env)->ReleaseStringUTFChars(env, access_key_secret, c_access_key_secret);
    (*env)->ReleaseStringUTFChars(env, security_token, c_security_token);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_topic
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1topic
        (JNIEnv *env, jclass obj, jlong config, jstring topic) {
    const char *c_topic = (*env)->GetStringUTFChars(env, topic, NULL);
    log_producer_config_set_topic((log_producer_config *) config, c_topic);
    (*env)->ReleaseStringUTFChars(env, topic, c_topic);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_add_tag
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1add_1tag
        (JNIEnv *env, jclass obj, jlong config, jstring key, jstring value) {
    const char *c_key = (*env)->GetStringUTFChars(env, key, NULL);
    const char *c_value = (*env)->GetStringUTFChars(env, value, NULL);
    log_producer_config_add_tag((log_producer_config *) config, c_key, c_value);
    (*env)->ReleaseStringUTFChars(env, key, c_key);
    (*env)->ReleaseStringUTFChars(env, value, c_value);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_packet_log_bytes
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1packet_1log_1bytes
        (JNIEnv *env, jclass obj, jlong config, jint num) {
    log_producer_config_set_packet_log_bytes((log_producer_config *) config, num);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_packet_log_count
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1packet_1log_1count
        (JNIEnv *env, jclass obj, jlong config, jint num) {
    log_producer_config_set_packet_log_count((log_producer_config *) config, num);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_packet_timeout
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1packet_1timeout
        (JNIEnv *env, jclass obj, jlong config, jint num) {
    log_producer_config_set_packet_timeout((log_producer_config *) config, num);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_max_buffer_limit
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1max_1buffer_1limit
        (JNIEnv *env, jclass obj, jlong config, jint num) {
    log_producer_config_set_max_buffer_limit((log_producer_config *) config, num);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_send_thread_count
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1send_1thread_1count
        (JNIEnv *env, jclass obj, jlong config, jint num) {
    log_producer_config_set_send_thread_count((log_producer_config *) config, num);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_persistent
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1persistent
        (JNIEnv *env, jclass obj, jlong config, jint num) {
    log_producer_config_set_persistent((log_producer_config *) config, num);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_persistent_file_path
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1persistent_1file_1path
        (JNIEnv *env, jclass obj, jlong config, jstring path) {
    const char *c_path = (*env)->GetStringUTFChars(env, path, NULL);
    log_producer_config_set_persistent_file_path((log_producer_config *) config, c_path);
    (*env)->ReleaseStringUTFChars(env, path, c_path);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_persistent_force_flush
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1persistent_1force_1flush
        (JNIEnv *env, jclass obj, jlong config, jint num) {
    log_producer_config_set_persistent_force_flush((log_producer_config *) config, num);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_persistent_max_file_count
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1persistent_1max_1file_1count
        (JNIEnv *env, jclass obj, jlong config, jint num) {
    log_producer_config_set_persistent_max_file_count((log_producer_config *) config, num);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_persistent_max_file_size
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1persistent_1max_1file_1size
        (JNIEnv *env, jclass obj, jlong config, jint num) {
    log_producer_config_set_persistent_max_file_size((log_producer_config *) config, num);
}

/*
 * Class:     com_aliyun_sls_android_producer_LogProducerConfig
 * Method:    log_producer_config_set_persistent_max_log_count
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1persistent_1max_1log_1count
        (JNIEnv *env, jclass obj, jlong config, jint num) {
    log_producer_config_set_persistent_max_log_count((log_producer_config *) config, num);
}

JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1using_1http(
        JNIEnv *env, jclass clazz, jlong config, jint num) {
    log_producer_config_set_using_http((log_producer_config *) config, num);
}

JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1net_1interface(
        JNIEnv *env, jclass clazz, jlong config, jstring net_interface) {
    const char *c_net_interface = (*env)->GetStringUTFChars(env, net_interface, NULL);
    log_producer_config_set_net_interface((log_producer_config *) config, c_net_interface);
    (*env)->ReleaseStringUTFChars(env, net_interface, c_net_interface);
}

JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1connect_1timeout_1sec(
        JNIEnv *env, jclass clazz, jlong config, jint num) {
    log_producer_config_set_connect_timeout_sec((log_producer_config *) config, num);
}

JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1send_1timeout_1sec(
        JNIEnv *env, jclass clazz, jlong config, jint num) {
    log_producer_config_set_send_timeout_sec((log_producer_config *) config, num);
}

JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1destroy_1flusher_1wait_1sec(
        JNIEnv *env, jclass clazz, jlong config, jint num) {
    log_producer_config_set_destroy_flusher_wait_sec((log_producer_config *) config, num);
}

JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1destroy_1sender_1wait_1sec(
        JNIEnv *env, jclass clazz, jlong config, jint num) {
    log_producer_config_set_destroy_sender_wait_sec((log_producer_config *) config, num);
}

JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1compress_1type(
        JNIEnv *env, jclass clazz, jlong config, jint num) {
    log_producer_config_set_compress_type((log_producer_config *) config, num);
}

JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1ntp_1time_1offset(
        JNIEnv *env, jclass clazz, jlong config, jint num) {
    log_producer_config_set_ntp_time_offset((log_producer_config *) config, num);
}

JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1max_1log_1delay_1time(
        JNIEnv *env, jclass clazz, jlong config, jint num) {
    log_producer_config_set_max_log_delay_time((log_producer_config *) config, num);
}

JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1drop_1delay_1log(
        JNIEnv *env, jclass clazz, jlong config, jint num) {
    log_producer_config_set_drop_delay_log((log_producer_config *) config, num);
}

extern JavaVM *g_VM;
jobject g_time_func;

unsigned int set_get_time_unix_func() {
    if (NULL == g_VM) {
        return time(NULL);
    }

    JNIEnv *env = NULL;
    if ((*g_VM)->AttachCurrentThread(g_VM, &env, NULL) != JNI_OK) {
        return time(NULL);
    }
    //通过全局变量g_obj 获取到要回调的类
    jclass java_class = (*env)->GetObjectClass(env, g_time_func);
    if (java_class == 0) {
        (*g_VM)->DetachCurrentThread(g_VM);
        return time(NULL);
    }
    //获取要回调的方法ID
    jmethodID java_callback_id = (*env)->GetMethodID(env, java_class,
                                                     "getTimeUnix",
                                                     "()J");
    if (java_callback_id == NULL) {
        return time(NULL);
    }
    //执行回调
    jlong time_unix = (*env)->CallLongMethod(env, g_time_func, java_callback_id);
    //释放当前线程
    (*g_VM)->DetachCurrentThread(g_VM);
    env = NULL;
    return time_unix;
}

JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1get_1time_1unix_1func(
        JNIEnv *env, jclass clazz, jobject func) {
    if (func != NULL) {
        g_time_func = (*env)->NewGlobalRef(env, func);
        log_set_get_time_unix_func(set_get_time_unix_func);
    }
}

JNIEXPORT jint JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1is_1valid(
        JNIEnv *env, jclass clazz, jlong config) {
    return log_producer_config_is_valid((log_producer_config *) config);
}

JNIEXPORT jint JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1persistent_1config_1is_1enabled(
        JNIEnv *env, jclass clazz, jlong config) {
    return log_producer_persistent_config_is_enabled((log_producer_config *) config);
}

JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1drop_1unauthorized_1log(
        JNIEnv *env, jclass clazz, jlong config, jint num) {
    return log_producer_config_set_drop_unauthorized_log((log_producer_config *) config, num);
}

JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1source(JNIEnv *env, jclass clazz,
                                                                                          jlong config,
                                                                                          jstring source) {
    const char *c_source = (*env)->GetStringUTFChars(env, source, NULL);
    log_producer_config_set_source((log_producer_config *) config, c_source);
    (*env)->ReleaseStringUTFChars(env, source, c_source);
}

JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1callback_1from_1sender_1thread(
        JNIEnv *env, jclass clazz, jlong config, jint num) {
    return log_producer_config_set_callback_from_sender_thread((log_producer_config *) config, num);
}

JNIEXPORT void JNICALL
Java_com_aliyun_sls_android_producer_LogProducerConfig_log_1producer_1config_1set_1http_1header_1inject(JNIEnv *env,
                                                                                                        jclass clazz,
                                                                                                        jlong config,
                                                                                                        jobject injector) {
    sls_set_android_http_inject(env, config, injector);
}

#ifdef __cplusplus
}
#endif
#endif

